version: '3.7'

services:
  vector-unitech-api:
    image: ${DOCKER_REGISTRY-}vectorunitechapi
    build:
      context: .
      dockerfile: Vector-unitech-api/Dockerfile
    networks:
      - code-network
    environment:
      TZ: 'America/Sao_Paulo'
      ASPNETCORE_ENVIRONMENT: 'Staging'
      TokenConfigurations__SecretJWTKey: '90614080-bfa4-4fa0-973c-334b5052cbf3'
      TokenConfigurations__Minutes: '60'
      TokenConfigurations__Issuer: 'API-Vector'
      TokenConfigurations__FinalExpiration: '120'
      TokenConfigurations__Audience: 'API-Vector'
      SentryDsn: 'https://324ceb9812d247d893cba71fed6660da@sentry.io/2616337'
      Kestrel__Certificates__Development__Password: '18cc4c2b-7465-4776-9e22-2aaadc58751e'
      RedisServer: 'redis_vector'
    ports:
      - "5000:80"
   

  redis:
    image: redis:6.2.5-alpine
    environment:
      TZ: 'America/Sao_Paulo'
    restart: always
    command: redis-server 
    container_name: redis_vector
    networks:
      - code-network
    ports:
     - "6379:6379"

     
networks:
    code-network:
        driver: bridge

